# Generated by Django 4.2 on 2026-06-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_userfavoritestation_stationreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='ocm_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='source',
            field=models.CharField(choices=[('OCM', 'Open Charge Map'), ('ECOCHARGE', 'EcoCharge Registered')], default='ECOCHARGE', max_length=20),
        ),
    ]
