# Generated by Django 4.2 on 2026-06-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_chargingstation_ocm_id_chargingstation_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='source',
            field=models.CharField(choices=[('OCM', 'Open Charge Map'), ('ECOCHARGE', 'EcoCharge Registered'), ('KAGGLE', 'Kaggle / HuggingFace Imported')], default='ECOCHARGE', max_length=20),
        ),
    ]
