# Generated by Django 4.2 on 2026-06-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_alter_chargingstation_source'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chargingstation',
            index=models.Index(fields=['status'], name='stations_ch_status_ed06a4_idx'),
        ),
    ]
