# Generated by Django 4.2 on 2026-07-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_add_status_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chargingstation',
            name='stations_ch_status_ed06a4_idx',
        ),
    ]
