# Generated by Django 4.2 on 2026-07-07 10:16

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='knowledgedocument',
            name='knowledge_source_idx',
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='knowledge_content_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
