# Generated by Django 4.2 on 2026-06-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance_km', models.FloatField()),
                ('battery_start_percent', models.FloatField()),
                ('battery_end_percent', models.FloatField(blank=True, null=True)),
                ('predicted_battery_readings', models.JSONField(default=list)),
                ('actual_battery_readings', models.JSONField(default=list)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
